### ISSUE TITLE
Main Features Checklist

### ISSUE THREAD

**Issue by Lamby777** [Lamby777/brainfuck-rs#2]
Checklist of important subcommands to add before focusing on smaller features:

- [x] `yx create`
- [x] `yx create <path>`

- [ ] `yx list`
- [ ] `yx list missing`
- [ ] `yx list by <tag>`

- [ ] `yx clean`
- [ ] `yx mv <old> <new>`
- [ ] `yx purge`
- [ ] `yx purge yes`

- [ ] `yx add <file> <tag>`
- [ ] `yx rm <file> <tag>`

- [ ] `yx constraint <constraint>`
- [ ] `yx free`

- [ ] `yx blanket <tag>`
- [ ] `yx forget <tag>`

- [ ] `yx render`
- [ ] `yx render sym`
- [ ] `yx render name`

**Comment by Lamby777** [comment]
wrong repo 💀
